export const gridSize = 20;
export const refreshTime = 750;
export const numberOfFruitSpawned = 3;
export const turnIntervalBetweenFruitSpawn = 4;
export const numberOfTailAddedAfterEating = 1;
export const scoresAfterEveryFruit = 7;
export const initialLength = 4;
export const mainMenuTransitionDuration = 250;
export const delayUntilGameStarts = 500 + mainMenuTransitionDuration;
export const placeholderUsername = "Snakeman69";
export const placeholderPassword = "5n4k3m4n69"